name: CI/CD Pipeline for Initial Execution Check

on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - development
      - main

jobs:
  initial-execution-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r automation/behave_python/requirements.txt

    - name: Check Behave tests initial execution
      run: |
        cd automation/behave_python
        for feature in features/*.feature; do
          behave --tags @initial-check $feature &
        done
      continue-on-error: true

    - name: Check API validation scripts initial execution
      run: |
        for script in python_scripts/*.py; do
          python $script &
        done
      continue-on-error: true