name: CI/CD Pipeline for Testing

on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - development
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r automation/behave_python/requirements.txt

    - name: Run Behave tests
      run: |
        cd automation/behave_python
        behave

    - name: Run API validation scripts
      run: |
        python python_scripts/min_value_of_whatsOnIt.py
        python python_scripts/price_validation.py
        python python_scripts/price_validation_ALL_PRODUCTS.py
        python python_scripts/pdp_validation/pdp_file_c.py
        python python_scripts/pdp_validation/pdp_validation.py

    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: |
          automation/behave_python/reports/
          python_scripts/reports/