name: CI Pipeline for Automation Scripts

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r automation/behave_python/requirements.txt

    # Step 4: Run Behave tests
    - name: Run Behave tests
      run: |
        cd automation/behave_python
        behave --junit --junit-directory=junit_results

    # Step 5: Upload test results (optional, for reporting)
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: automation/behave_python/junit_results/